### ISSUE TITLE
Why this doesn't work for MCX:NATURALGASV2020 ?

### ISSUE THREAD

**Issue by rahulmr** [deathlyface/python-tradingview-ta#11]
I tried using the script for `NSE:SBIN` and other Indian stocks it works great but it does not work with `MCX:...` or may be with futures. Do you know if this can be implemented?

**Comment by deathlyface** [comment]
Hey rahulmr, 

It seems like TradingView does not support technical analysis for `MCX:...`, since there's no technical tab on TV's website. I can't do anything about it. Other futures works with this library, I'll edit the documentation.

Thanks for informing me.
