### ISSUE TITLE
Extension of the API in Indicator Values

### ISSUE THREAD

**Issue by AtakanTekparmak** [deathlyface/python-tradingview-ta#13]
If any developer with necessary time and Python provess could extend the repo so we could get the closing value and values of the included indicators with embedded functions, that would be great.

**Comment by euvgub** [comment]
Access to indicators values dictionary:
handler.get_analysis().indicators

**Comment by AtakanTekparmak** [comment]
Thank you for your answer. I wish you and anyone that helps maintain this repository well and hope that it gets maintained for years to come!
