### ISSUE TITLE
Read Currencies

### ISSUE THREAD

**Issue by GiraHacker** [deathlyface/python-tradingview-ta#14]
How can I read currencies?
Can you post an example?

such as EURUSD

**Comment by deathlyface** [comment]
Hello, GiraHacker,
To get the technical analysis for EURUSD or other forex, you can use this code:

```python
from tradingview_ta import TA_Handler, Interval

handler = TA_Handler()
handler.set_symbol_as("EURUSD")
handler.set_exchange_as_forex()
handler.set_screener_as_forex()
handler.set_interval_as(Interval.INTERVAL_1_DAY)
print(handler.get_analysis().summary)
// output: {'RECOMMENDATION': 'BUY', 'BUY': 16, 'SELL': 3, 'NEUTRAL': 8}
```

Tested and compared with data from tradingview:
![eurusd screeenshot](https://user-images.githubusercontent.com/40331046/101421015-fa3ff200-3925-11eb-869c-22f512241fc3.png)

You can also visit the documentation [here](https://python-tradingview-ta.readthedocs.io/en/latest/usage.html).
