### ISSUE TITLE
Road to zero. Because for any Interval.INTERVAL_x_MINUTES it`s return only 1Day data. You can check it by comparing indicator value

### ISSUE THREAD

**Issue by euvgub** [deathlyface/python-tradingview-ta#15]
Road to zero. Because for signed user any Interval.INTERVAL_x_MINUTES it`s return only 1Day data. You can check it by comparing indicator value on chart with get_analysis().indicators values. Seems like in unpaid tradingview only 1Day technical analysis available and handler.set_interval_as() interval doesn't matter
And for not signed user returned data = delayed 15 min data

**Comment by deathlyface** [comment]
Hello euvgub,

You can't just use INTERVAL_x_MINUTES and replace the x with anything. It will cause an error and defaulted to 1 day. Please refer to the documentation ([setting-the-interval](https://python-tradingview-ta.readthedocs.io/en/latest/usage.html#setting-the-interval)) for available intervals. 

I'll close this issue. Please reopen if you still have a similar problem.

**Comment by euvgub** [comment]
```
intervals = ['Interval.INTERVAL_1_MINUTE','Interval.INTERVAL_5_MINUTES']
for interval in intervals:
    tesla.set_interval_as(interval)
```
Seems like we need correct cookies for signed user

**Comment by deathlyface** [comment]
Sign-in is not required. In the `intervals` list, both `'Interval.INTERVAL_1_MINUTE'` and `'Interval.INTERVAL_5_MINUTES'` are strings. Please remove the apostrophe (').

`intervals = [Interval.INTERVAL_1_MINUTE, Interval.INTERVAL_5_MINUTES]`

**Comment by euvgub** [comment]
Thanks, I`ll process every Interval in Thread

**Comment by euvgub** [comment]
For not signed user result = data delayed 15 min

**Comment by deathlyface** [comment]
I didn't know about that. Do you have more information? Links? 

I tried both signed-in and not signed-in and the result is the same (on 1-minute interval).

**Comment by euvgub** [comment]
Stock Screener - Time interval other than 1Day - > pop-up 

"Monitor changes by the minute with
our Screener's intraday time frames Be the first to know when an asset matches your chosen criteria, with our
Screener's intraday time frame settings - only on our upgraded plans.
30-Day Free Trial"
