### ISSUE TITLE
Add Pivot Table Extraction Too!

### ISSUE THREAD

**Issue by windowshopr** [deathlyface/python-tradingview-ta#16]
Would love to see a plugin made to pull the Pivots Table from the Technicals Page too! :) Love the tool, works great!

**Comment by deathlyface** [comment]
Thanks for the idea! I'll consider adding it.

**Comment by deathlyface** [comment]
Hey @windowshopr, 
I just realized that python-tradingview-ta supports extracting pivots. Please refer to the `analysis.indicators` documentation on https://python-tradingview-ta.readthedocs.io/en/latest/usage.html#indicator-values. Hope this helps.

**Comment by windowshopr** [comment]
Hey there they are! 😁 awesome!! Thanks a lot!!!
