### ISSUE TITLE
How to find necessary data from DevTools

### ISSUE THREAD

**Issue by kimble72** [deathlyface/python-tradingview-ta#17]
hi @deathlyface what a neat script you have

I love the readme you've done, it's very clear.

Wanted to try the same for a local broker (www.nordnet.fi). Target would be to get prices from this broker, but am not that good with DevTools.
I wonder how could I get to that step that you mentioned in your 'How it Works' // 'TradingView API' part. Especially I liked the lean way of expressing the url, the description of the POST and also the result.
This lean way of expressing them helped me a lot of making it work for me in py.

But could I, and how, do the same for my local broker? Would appreciate any good click instructions on how to get those url and post's in a clean way defined.

Looking fwd to hear from you guys.

br
kimmo

**Comment by deathlyface** [comment]
Hey @kimble72,
I believe you don't need the DevTools. Check out the Nordnet API documentation: [https://www.nordnet.fi/externalapi/docs](https://www.nordnet.fi/externalapi/docs) and search for `PRICE_INFO`. Hope this helps.

**Comment by kimble72** [comment]
hi thanks @deathlyface that was a good observation from your side
