### ISSUE TITLE
find more example

### ISSUE THREAD

**Issue by AmirArsalan73** [deathlyface/python-tradingview-ta#22]
hello. the examples for this project is not enough. how can I receive data for CHFJPY symbol in FXCM exchange?

**Comment by deathlyface** [comment]
Hello @AmirArsalan73,
You can refer to the documentation on "[Setting the exchange](https://python-tradingview-ta.readthedocs.io/en/latest/usage.html#setting-the-exchange)". For forex, set the exchange using `handler.set_exchange_as_forex()`

So, your code should look like this:
```python
from tradingview_ta import TA_Handler, Interval
handler = TA_Handler()
handler.set_symbol_as("CHFJPY")
handler.set_exchange_as_forex()
handler.set_screener_as_forex()
handler.set_interval_as(Interval.INTERVAL_1_DAY)
analysis = handler.get_analysis()
print(analysis.summary)
```

![Screenshot from 2021-01-14 07-13-16](https://user-images.githubusercontent.com/40331046/104527767-12e3ac00-5638-11eb-8c39-4e133fde6987.png)

**Comment by deathlyface** [comment]
Note: Even though you want to use the FXCM exchange, tradingview use FX_IDC for the technical analysis, as you can see when you inspect your request:
![Screenshot from 2021-01-14 07-20-37](https://user-images.githubusercontent.com/40331046/104528149-0b70d280-5639-11eb-8875-897d014b52d3.png)

**Comment by AmirArsalan73** [comment]
Thanks a lot 🙌🙌🙌
