### ISSUE TITLE
Golang version of tradingview-ta

### ISSUE THREAD

**Issue by deathlyface** [deathlyface/python-tradingview-ta#24]
Anyone interested in the golang version of tradingview-ta? Tell me below and I'll consider creating it.

**Comment by bt** [comment]
Hey there, I just came across this library and as a Golang developer, I'd love to use a similar library.

I can help you develop it, just start a new repository and put some boilerplate down 😄

**Comment by deathlyface** [comment]
Hi @bt,

I just created the repo [deathlyface/gotvta](https://github.com/deathlyface/gotvta). It's still a WIP.

Currently, it can retrieve data from TradingView. It can also compute indicators into readable buy/sell. Maybe I need some help getting values from a JSON. I'm new to golang.
