### ISSUE TITLE
max retries exceed with url

### ISSUE THREAD

**Issue by raakeshtomarnew** [deathlyface/python-tradingview-ta#26]
Max retries exceeded with url: /india/scan (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object
 at 0x000001E25BF708E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or
 established connection failed because connected host has failed to respond')) BPCL

**Comment by deathlyface** [comment]
Hey @raakeshtomarnew,

Thanks for creating this issue. Can you reply with your code? What interval and exchange did you use?

**Comment by raakeshtomarnew** [comment]
Thanks for response
Now problem is solved.
