### ISSUE TITLE
when using interval=Interval.INTERVAL_1_MINUTES, it gives attribute error

### ISSUE THREAD

**Issue by ZAAHAR** [deathlyface/python-tradingview-ta#27]
![Screenshot_2021-02-09_21-45-20](https://user-images.githubusercontent.com/67459663/107395929-49232700-6b23-11eb-9461-470e17c96ac6.jpg)

**Comment by deathlyface** [comment]
Hey @ZAAHAR,

Please try using `INTERVAL_1_MINUTE`, without `S` at the end. Also, run `dir(Interval)` to see what intervals are available.

**Comment by ZAAHAR** [comment]
Thanks
