### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Racho24** [deathlyface/python-tradingview-ta#28]
Hey, 

Tried to loop through some symbols and got this error message:

..., , in get_analysis
    raise Exception("Can't access TradingView's API. HTTP status code: {}.".format(response.status_code))
Exception: Can't access TradingView's API. HTTP status code: 404.

any help?!

**Comment by deathlyface** [comment]
Hi @Racho24,
Can you reply with your code?

**Comment by Racho24** [comment]
`from tradingview_ta import TA_Handler, Interval


def get_technicals(symbol):
    try:
        exchange = "FWB"
        handler = TA_Handler(
            symbol=symbol,
            exchange=exchange,
            screener="germay",
            interval=Interval.INTERVAL_1_DAY
        )
        summary = handler.get_analysis().summary
    except:
        exchange = "XETR"
        handler = TA_Handler(
            symbol=symbol,
            exchange=exchange,
            screener="germay",
            interval=Interval.INTERVAL_1_DAY
        )
        summary = handler.get_analysis().summary
    return summary


print(get_technicals('ADS'))`

**Comment by deathlyface** [comment]
I think you misspelled the screener. Try using `germany` instead of `germay`. Tested and works for me.
```python
>>> handler = TA_Handler(
...     symbol="ADS",
...     exchange="FWB",
...     screener="germany",
...     interval=Interval.INTERVAL_1_DAY
... )
>>> handler.get_analysis().summary
{'RECOMMENDATION': 'BUY', 'BUY': 16, 'SELL': 1, 'NEUTRAL': 9}
```
If this fixes your error, you may close this issue. Otherwise, reply with details.

**Comment by Racho24** [comment]
ahh sorry for that ... and thanks for the help ;)

**Comment by sertackeskin** [comment]
Hi @brian-the-dev , 

I would like to obtain data for currencies and her is my code:

    symHandler = TA_Handler(
        symbol='USDTRY',
        screener="forex",
        exchange="FXCM",
        interval=Interval.INTERVAL_1_HOUR
                
and output is : raise Exception("Exchange or symbol not found.")

what is the reason of problem. I tried every exchange but couldnt solve exception problem. I tried 'OANDA' ,  'FXCM', 'FOREX.com'

**Comment by brian-the-dev** [comment]
Hey @sertackeskin,

You can use `Exchange.FOREX` or `"FX_IDC"` as the exchange:

```python
from tradingview_ta import TA_Handler, Interval, Exchange

symHandler = TA_Handler(
    symbol='USDTRY',
    screener="forex",
    exchange=Exchange.FOREX,
    interval=Interval.INTERVAL_1_HOUR
)
```

**Comment by sertackeskin** [comment]
thanks for your comment. I got it worked. I have another issue on XAUTRYG

from tradingview_ta import TA_Handler, Interval, Exchange

symHandler = TA_Handler(
    symbol='XAUTRYG',
    screener="cfd",
    exchange='TVC',
    interval=Interval.INTERVAL_1_HOUR
)

and output is : raise Exception("Exchange or symbol not found.")

**Comment by brian-the-dev** [comment]
@sertackeskin,

Your issue is similar to #11. There's no "Technicals" tab on their site, meaning it's not supported. Compare `"XAUTRYG"` to `"USDTRY"`:

![image](https://user-images.githubusercontent.com/40331046/122739025-bf435180-d2ac-11eb-89d8-527a5c234e51.png)

![image](https://user-images.githubusercontent.com/40331046/122739141-e4d05b00-d2ac-11eb-8797-a0d1508d887b.png)
