### ISSUE TITLE
TA_Handler processing forever and no responsive

### ISSUE THREAD

**Issue by tuansacer** [deathlyface/python-tradingview-ta#36]
Dear creator.
Somes first time ran normally.
Then TA_Handler function processing forever in a loop and does not respond result. 
My code example:
```
import time
from tradingview_ta import TA_Handler, Interval, Exchange

while True:
    try:
        s = TA_Handler(symbol="EURUSD",
                       screener="forex",
                       exchange=Exchange.FOREX,
                       interval=Interval.INTERVAL_1_MINUTE)
        print(s.get_analysis())
        time.sleep(30)
    except Exception as e:
        print(str(e))
```
Plz help me

**Comment by deathlyface** [comment]
Hello @tuansacer,

What do you mean by processing forever? It's working fine when I tried running it.

![Screenshot from 2021-03-25 07-41-13](https://user-images.githubusercontent.com/40331046/112401676-a5da4a00-8d3d-11eb-840a-f2fc9ef96361.png)

The `get_analysis()` function returns an `Analysis` object like this: `<tradingview_ta.main.Analysis object at 0x7fe19cf97e80>`. The `Analysis` object contains the technical analysis, time, symbol, indicators, etc. For example, you can modify your code into `print(s.get_analysis().summary)` to get the summary. 

```python
# Full Code
import time
from tradingview_ta import TA_Handler, Interval, Exchange

while True:
    try:
        s = TA_Handler(symbol="EURUSD",
                       screener="forex",
                       exchange=Exchange.FOREX,
                       interval=Interval.INTERVAL_1_MINUTE)
        print(s.get_analysis().summary)
        time.sleep(30)
    except Exception as e:
        print(str(e))
```

![Screenshot from 2021-03-25 07-48-32](https://user-images.githubusercontent.com/40331046/112402119-8263cf00-8d3e-11eb-9930-85f2e35cc56e.png)

Please see the [documentation](https://python-tradingview-ta.readthedocs.io/en/latest/usage.html#getting-the-analysis) for more details.

If this resolves your issue, you may close this issue. If you have another question or still having a problem, send me a reply.

**Comment by tuansacer** [comment]
First, thank you for the early response.
Monday, sorry that I didn't mean it. I will re-explain my problem.

That's when I run the code in a continuous loop. The first time running was very stable (It takes about 1-2s to complete a data). 
But then for a while the program stops but no error occurs.
Like image is program stopped get data at 2021-03-25 12:41:26 (No error occurs + The script status is running)
Plz help me...

![image](https://user-images.githubusercontent.com/37577474/112478921-0fdb0980-8da7-11eb-9ae0-8753b46a2c4f.png)

**Comment by deathlyface** [comment]
I understand now...

Please give me some time to look it up and I'll give you an update soon.

**Comment by tuansacer** [comment]
Yes. Thank you so much

**Comment by deathlyface** [comment]
I tested the code for hours and can't figure out the problem. Probably it's caused by network problems/no response from the server. I added timeout into v3.2.3. Please update (`pip install -U tradingview_ta`) and try adding it.

```python
s = TA_Handler(
    symbol="EURUSD",
    screener="forex",
    exchange=Exchange.FOREX,
    interval=Interval.INTERVAL_1_MINUTE,
    timeout=10 # 10 seconds timeout
)
```

**Comment by tuansacer** [comment]
It's working for me. Thank for your support

**Comment by deathlyface** [comment]
You're welcome. You may reopen this issue if you have a similar problem.
