### ISSUE TITLE
AttributeError: type object 'TA_Handler' has no attribute 'set_symbol_as'

### ISSUE THREAD

**Issue by FinagleLord** [deathlyface/python-tradingview-ta#9]
I've been trying to solve this all night, but I finally give up. Anyone have any idea what I'm doing wrong? I'm trying to run the demo script.

**Comment by deathlyface** [comment]
Hello FinagleLord, it seems to be working fine for me. The set_symbol_as function is only available in >=3.1.0. Please upgrade using `pip install --upgrade tradingview_ta`. Please let me know if the problem still exists.

**Comment by FinagleLord** [comment]
Resolved, thanks for your contribution to the open source community :) @deathlyface

**Comment by deathlyface** [comment]
My pleasure. I'll close this issue.
